files:
  include: 'app/**/*.scss'
rules:
  class-name-format: 0
  empty-args: 2
  force-pseudo-nesting: 2
  mixin-name-format: 0
  mixins-before-declarations: 2
  no-ids: 0
  no-transition-all: 2
  no-url-domains: 0
  no-url-protocols: 0
  property-sort-order: 0
  pseudo-element: 0
  single-line-per-selector: 2
  trailing-semicolon: 2
